### ISSUE TITLE
OptionsMenu className attribute doesn't work

### ISSUE THREAD

**Issue by ryomtoob** [dequelabs/cauldron-react#161]
Applying a css class like so has no effect:
`<OptionsMenu className='hamburger'></OptionsMenu>`

Easy workaround:
`<div className='hamburger'><OptionsMenu></OptionsMenu></div>`

I believe the cause is that the OptionsMenu component takes in the className prop, but fails to pass it into the OptionsMenuWrapper component.

**Comment by scurker** [comment]
Yup, looks like this is something we missed.
