### ISSUE TITLE
Tests randomly failing on CI

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/cauldron-react#190]
I've only been working on this library a bit recently and have had two random (unrelated to the changes I had made) test failures:

1. https://circleci.com/gh/dequelabs/cauldron-react/830
2. https://circleci.com/gh/dequelabs/cauldron-react/799

Rerunning the tests seemed to have fixed it. This is probably worth looking into.

**Comment by stephenmathieson** [comment]
Another random failure: https://circleci.com/gh/dequelabs/cauldron-react/860

**Comment by stephenmathieson** [comment]
And another: https://circleci.com/gh/dequelabs/cauldron-react/867

**Comment by schne324** [comment]
more of this still happening frequently ([example](https://circleci.com/gh/dequelabs/cauldron-react/1079?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link))...

```
ENOMEM: not enough memory, read

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:509:43)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
```

For this issue, I think we should explore the [`maxWorkers`](https://jestjs.io/docs/en/cli#--maxworkersnumstring) jest cli option. After quick googling it appears that tons of people have "fixed" this issue by running the tests like with the flag `-w 1` to allow for only 1 worker
