### ISSUE TITLE
z-index issue

### ISSUE THREAD

**Issue by roman-bytes** [dequelabs/cauldron-react#205]
The z-index of the menu should be higher than the toast.

![Screen Shot 2019-09-10 at 9 25 42 AM](https://user-images.githubusercontent.com/4601329/64641643-981ed700-d3da-11e9-86a8-733530e496e2.png)

**Comment by schne324** [comment]
I think this is actually a dequelabs/pattern-library issue: https://github.com/dequelabs/pattern-library/blob/master/lib/variables.less#L122-L123 and https://github.com/dequelabs/pattern-library/blob/master/lib/variables.less#L120

**Comment by roman-bytes** [comment]
created new issue here: https://github.com/dequelabs/pattern-library/issues/127
