### ISSUE TITLE
Toast demo layout bugs

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron-react#217]
The close buttons in the confirmation / caution are not displayed inline (aka flex) but are on their own lines (see screenshot)

<img width="899" alt="Screen Shot 2019-09-24 at 10 54 57 AM" src="https://user-images.githubusercontent.com/3180185/65537279-c9f36b80-deb9-11e9-828b-192db570b5ed.png">

All we need to do is set `display: flex` on the "dqpl-toast" element (which should probably happen in dequelabs/pattern-library). Here is the expected layout:

<img width="892" alt="Screen Shot 2019-09-24 at 10 55 06 AM" src="https://user-images.githubusercontent.com/3180185/65537339-e55e7680-deb9-11e9-816e-4479095232b3.png">

**Comment by jeeyyy** [comment]
For anyone looking at the issue on a later date, see comment - https://github.com/dequelabs/pattern-library/pull/128#discussion_r334575907 for some context.

**Comment by jeeyyy** [comment]
PR #232 fixes the issue.
