### ISSUE TITLE
Close <OptionsMenu> when user clicks outside

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/cauldron-react#57]
After opening a `<OptionsMenu />`, clicking outside of it should close it. Something like [this component](https://github.com/tj/react-click-outside) is a good starting place.

**Comment by schne324** [comment]
👍 clicks outside the sidebar should do the same

**Comment by stephenmathieson** [comment]
Hmm, not sure I agree there. On https://dequelabs.github.io/cauldron-react/, we _want_ the sidebar to stay open (assuming there's enough horizontal space).

**Comment by schne324** [comment]
ah sorry @stephenmathieson , I forgot to specify that the above statement applies to when the sidebar is collapsible (which happens at smaller viewports (I think < 1024))

**Comment by stephenmathieson** [comment]
Right. I figured that (see previous comment).

It might be strange for the component to function differently based on device/viewport size, but I don't have strong opinions here.

**Comment by schne324** [comment]
It inherently behaves differently based on viewport size. In wider views it's locked and the trigger to toggle its visibility is hidden, while at narrow views it is not locked and toggle-able by the 🍔 trigger. I'm not too worried about this functionality so I would yield to this ticket applying to the sidebar and scope it for just the `<OptionsMenu />`

**Comment by scurker** [comment]
Also related #84
