### ISSUE TITLE
Close <OptionsMenu /> after selecting an option

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/cauldron-react#59]
Clicking an "option" of an `<OptionsMenu />` should close the menu.

**Comment by schne324** [comment]
What if clicking the option launches a modal? Returning focus to the trigger is the expected behavior for when a dialog closes.  Because of this, my opinion is to either leave this decision up to the implementer (it is easy to maintain a local "show" state to control the menu) or at most making this configurable via a `closeOnOptionClick` prop

**Comment by stephenmathieson** [comment]
Opening a modal from an option menu seems like a very strange UX pattern that I'd probably recommend against. Modals are intentionally interruptive; using them sparingly is recommended by most design/UX guidelines. Being required to interact with a modal after clicking a menu item sounds like a tedious experience from a users' perspective. I bet there's a better solution there 🤷‍♀️ 

Regardless of all that, I do understand what you're saying. If there's a logical reason for wanting to keep it open, then I'm fine with it.

**Comment by schne324** [comment]
fwiw, a deque product I work on that uses cauldron-react triggers modals from options in an options menu...so does twitter and facebook and github which makes me think this is a much more common ux pattern than you think.

**Comment by stephenmathieson** [comment]
Interesting. Can you show me an example?

**Comment by schne324** [comment]
Right here in github if you click the top-right menu item (the one with your avatar and a down arrow) the first clickable menu item is your "status"...when you click that, it opens a modal in which you can edit your status. let me know if you want me to show you other examples

**Comment by stephenmathieson** [comment]
Hmm, weird, ok

**Comment by schne324** [comment]
perhaps we could support both via a prop. `<Option closeOnClick />`.

@stephenmathieson wdyt?
