### ISSUE TITLE
Remove UMD/unpkg build

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/cauldron-react#68]
I don't believe any projects are using it right now, so I'd like to remove it. No need to support stuff we don't use here...

Thoughts @schne324?

**Comment by stephenmathieson** [comment]
3 weeks have passed without a response. This tells me we can probably get rid of the UMD build. I'll hopefully do this next week.

**Comment by schne324** [comment]
sorry for the late response - yea I don't think we really need the UMD build
