### ISSUE TITLE
create <AccountActions /> (within topBar) component

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron-react#7]

**Comment by schne324** [comment]
https://pattern-library.dequelabs.com/composites/top-bar (click TOGGLE ACCOUNT ACTION)

**Comment by SantoshDeque** [comment]
https://pattern-library.dequelabs.com/composites/top-bar -- when clicked TOGGLE ACCOUNT ACTION, it shows Account Element(Drop down) in top bar.

![TopBar-Account-cauldron](https://user-images.githubusercontent.com/45222788/59582588-60173900-90f6-11e9-95bf-c45522fd816b.gif)

**Comment by scurker** [comment]
@SantoshDeque pattern-library.dequelabs.com is the vanilla version, this issue was for cauldron-react. You should be able to verify this on netlify: https://cauldron-react.netlify.com/composites/top-bar-menu

**Comment by SantoshDeque** [comment]
Verified with the url https://cauldron-react.netlify.com/composites/top-bar-menu

![TopBar-changes-working](https://user-images.githubusercontent.com/45222788/59611172-71813500-9138-11e9-868a-d05b9fa8c44d.gif)
