### ISSUE TITLE
Provide basic wireframes for the expand/collapse in extension UI

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron-react#71]
chevron up/down (details / summary-ish)

**Comment by schne324** [comment]
@awpearlm could you provide basic wireframes for the expand/collapse in extension UI?

**Comment by awpearlm** [comment]
https://preview.uxpin.com/cb78925e67d7ad2d003f75cfb3e2c49f1ebd7878#/pages/109560207

**Comment by aellsey** [comment]
@awpearlm blocked until you are able to create the wireframes.

**Comment by scurker** [comment]
@aellsey I have access to @awpearlm's designs.

**Comment by schne324** [comment]
@aellsey , @awpearlm and I didn't want to share the wireframes publicly so he has delivered it to @scurker
