### ISSUE TITLE
Strange behavior when using anchors within the <OptionsMenu>

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/cauldron-react#73]
If you put links within the `<OptionsMenu>` component, opening the menu causes the first link in the list to be "clicked". I have no idea why this is.

Example:

```js
<OptionsMenu>
  <OptionsMenuItem>
    <a href="/foo">foo</a>
  </OptionsMenuItem>
  <OptionsMenuItem>
    <a href="/bar">bar</a>
  </OptionsMenuItem>
  <OptionsMenuItem>
    <a href="/baz">baz</a>
  </OptionsMenuItem>
</OptionsMenu>

**Comment by stephenmathieson** [comment]
Clicking the link seems intermittent. When it does not happen, however, I'm unable to click the link within the menu item (with a keyboard; the mouse works fine).

**Comment by stephenmathieson** [comment]
I've narrowed this down a bit further. If the `<OptionsMenu>` is contained by a `<MenuItem>` (eg in a `<TopBar>`), this behavior is present. This might be a side-effect of the `<MenuItem>` component.

**Comment by stephenmathieson** [comment]
I figured it out - it's result of the `<MenuItem>` automatically clicking links:

https://github.com/dequelabs/cauldron-react/blob/9758e58eb12021ef188f95623520c84529f4914b/src/components/MenuItem/index.js#L27

It'd be nice to optionally disable this functionality.

**Comment by schne324** [comment]
great catch @stephenmathieson !

**Comment by stephenmathieson** [comment]
PR opened to optionally disable above functionality.

There's still an issue with anchors within an `<OptionsMenu>` (they cannot be "clicked" with a keyboard). I'm looking at this now.

**Comment by stephenmathieson** [comment]
The problem is that the `<a>` is removed from the tab order, so it never gets focused (and therefore never receives keyboard events).

A possible solution would be to write a utility similar to the above `click-link.js` file which clicks anchors when enter/space is pressed on the `<OptionsMenuItem>`. I'm going to do this in my app for now, but will add this functionality here if you like.

**Comment by stephenmathieson** [comment]
Should not have closed. Anchors still don't work properly.

**Comment by schne324** [comment]
We need a way for a menu item to click it's anchor without that click bubbling back up to create an infinite loop
