### ISSUE TITLE
Buttons are inline elements

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/cauldron-react#82]
The `<Button>` component has `display: block`, but native buttons are `display: inline-block`. This makes positioning the `<Button>` component more difficult (since we have to override styles).

Would you consider changing the `display` property of the `<Button>` component?

**Comment by schne324** [comment]
Yes, but this would be a fix in [dequelabs/pattern-library](https://github.com/dequelabs/pattern-library)

**Comment by schne324** [comment]
this change has been made in the pattern library
